### ISSUE TITLE
unexpected asyncio behavior

### ISSUE THREAD

**Issue by dragonwolfsp** [JessicaTegner/teamtalk.py#12]
Hello, I have run in to a problem with the asyncio setup. The setup seems to cause the entire running event to wait forever if you use ```await asyncio.sleep```. This also causes the list_user_accounts and list_banned_users functions to break and wait forever.

**Comment by JessicaTegner** [comment]
I think #8  is related to this.

But essentially, the error is somewhere in where we create and/or shedule tasks on the asyncio event loop
