### ISSUE TITLE
Event error

### ISSUE THREAD

**Issue by ghost** [JessicaTegner/teamtalk.py#13]
When using the bot example and installing the library via pip on Python 3.8 (since it doesn't work with version 3.11), I receive an AttributeError: Cannot change the id of a channel error almost with any event.

**Comment by ghost** [comment]
It works on python3.11, but the same error occurs.

**Comment by JessicaTegner** [comment]
This issue has been reported before. Can you try with the current master branch and let me know if the issue is still there

**Comment by ghost** [comment]
Thank you very much, especially for the update to tt5.15!

**Comment by ghost** [comment]
Thx.
