### ISSUE TITLE
api documents

### ISSUE THREAD

**Issue by ghost** [JessicaTegner/teamtalk.py#16]
Headings are displayed, but there is no information about what is behind them. Of course, I can download the source code and look there, but for beginners, this will not be the best solution.
I think something just didn't compile correctly.

**Comment by ghost** [comment]
For example, I can perform certain actions if the bot is kicked and so on, but how do I kick a user? Especially if I decided to look at the documentation for the first time. That's where the problems begin.

**Comment by ghost** [comment]
1.
The code example in the documentation is very old, without async and something else that I don't remember exactly.
2.
Also, I would recommend fixing the API documentation and adding examples for all methods, like how do I get the server name.
But, i don't have the API documentation. Maybe, if I have time, I will also make some fixes, because I like this project and its implementations, but I recommend adding examples.

**Comment by JessicaTegner** [comment]
Thanks for your suggestions.
I will keep it in mind for next time I get some free time, but before the next version of TeamTalk.py.
Anyone are more than welcome to improve the documentation, or add examples.
