### ISSUE TITLE
Audio functions

### ISSUE THREAD

**Issue by BlindMaster24** [JessicaTegner/teamtalk.py#26]
Hi! 

Is there a plan to add audio devices, including enabling/disabling voice activation and all features related to real-time audio, not just audio blocks?

**Comment by BlindMaster24** [comment]
@JessicaTegner ?

**Comment by JessicaTegner** [comment]
Hey.
I know that @blindelectron  has talked about wanting to add media file support, but other than that, using audio blocks should really be most of what you need for "voice transmission".
Do you have a specific usecase for getting the other features implemented?

**Comment by BlindMaster24** [comment]
@JessicaTegner
I'll soon suggest my options in the pull request.

Other questions.

1. 
How about adding examples to the README showing how to call SDK functions directly from your library, so newbies know how it works?

2. 
I have a question. Do you have Telegram or something so I can DM you if I have questions and so I don't lose track of you? Email's okay, but Telegram or something similar would be better. Thanks!

**Comment by BlindMaster24** [comment]
> Hey. I know that @blindelectron has talked about wanting to add media file support, but other than that, using audio blocks should really be most of what you need for "voice transmission". Do you have a specific usecase for getting the other features implemented?


Sometimes there's a need to stream specifically through media files, not voice. And voice activations and so on are also necessary, especially if it's a music bot, or, for example, a voice chat roulette bot, although that's a strange example.

**Comment by BlindMaster24** [comment]
> Hey. I know that @blindelectron has talked about wanting to add media file support, but other than that, using audio blocks should really be most of what you need for "voice transmission". Do you have a specific usecase for getting the other features implemented?

I can add everything that @blindelectron wanted, that's not a problem. I'm interested in whether you, as the owner of ripo, were planning on adding this?

**Comment by BlindMaster24** [comment]
@JessicaTegner 
I'll submit a PR with my suggestions soon.
Other questions.
1. 
How about adding examples to the README showing how to call SDK functions directly from your library, so newbies know how it works?
2. 
I have a question. Do you have Telegram or something so I can DM you if I have questions and so I don't lose track of you? Email's okay, but Telegram or something similar would be better. Thanks!

**Comment by BlindMaster24** [comment]
@JessicaTegner Reply pls.

**Comment by JessicaTegner** [comment]
hi @BlindMaster24  sorry I haven't gotten back to this before.
Yes I want to add everything  that the sdk offers in a more accessible way.

The plan is not to be calling the sdk directly, only teamtalk.py.
I have a bunch of ways to be contacted, you should be able to find it on my website, and then we could exchange discord, or whatever else

**Comment by BlindMaster24** [comment]
@JessicaTegner done!
